### ISSUE TITLE
How to use R2rb to flip the `application.css.scss` on the fly?

### ISSUE THREAD

**Issue by mabras** [mzsanford/R2rb#16]
So I have a Rails app with bootstrap and bootstrap customization (theme). What I want is to flip the direction for all the styles of `application.css.scss`. Can I use this gem for this use case?

**Comment by mzsanford** [comment]
This game does not have any knowledge of SCSS syntax so it will probably create broken output if you call it with SCSS. The gem itself attempts to flip as much as it can but is intended as a starting point that might need human editing so it might not work well for your use case. If you want to try it you could try to integrate it into your asset pipeline so you generate something like `application.rtl.css` by running the `application.css` produced from your SCSS through R2rb.
